# Generated by Django 3.1.3 on 2020-12-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0003_auto_20201223_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='user',
        ),
    ]
