# Generated by Django 3.1.3 on 2020-12-23 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0004_auto_20201223_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='event_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.AddField(
            model_name='event',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
