# Generated by Django 3.1.3 on 2020-12-28 16:46

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cal', '0005_auto_20201223_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('event', 'user', 'email', 'action')},
        ),
    ]
