# Generated by Django 3.1.3 on 2020-12-28 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cal', '0006_auto_20201228_1746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('event', 'user')},
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='action',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='email',
        ),
    ]
